name: Build and deploy ASP.Net Core app to Azure Web App - medical-center-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # актуальная версия .NET

      - name: Restore
        run: dotnet restore ./MedicalCenter.sln

      - name: Build
        run: dotnet build ./MedicalCenter.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./MedicalCenterApi/MedicalCenterApi.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CFBD8C6B298F4D28AE28269826C17DEA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F13DC0F4C6741A2BDF6D588FD4BD811 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9A47D5A3453C429481523E60F7CA95CC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'medical-center-api'
          slot-name: 'Production'
          package: .
